//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeaturesOverlayPresentation {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutBox() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeaturesOverlayPresentation.AboutBox", typeof(AboutBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.DockStyle semelhante a Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle labelCompanyName_Dock {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Point semelhante a {X=142,Y=90}.
        /// </summary>
        internal static System.Drawing.Point labelCompanyName_Location {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.Padding semelhante a {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding labelCompanyName_Margin {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=0, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelCompanyName_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=269, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelCompanyName_Size {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 22.
        /// </summary>
        internal static int labelCompanyName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company Name.
        /// </summary>
        internal static string labelCompanyName_Text {
            get {
                return ResourceManager.GetString("labelCompanyName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.ContentAlignment semelhante a MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment labelCompanyName_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.DockStyle semelhante a Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle labelCopyright_Dock {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Point semelhante a {X=142,Y=60}.
        /// </summary>
        internal static System.Drawing.Point labelCopyright_Location {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.Padding semelhante a {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding labelCopyright_Margin {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=0, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelCopyright_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=269, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelCopyright_Size {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 21.
        /// </summary>
        internal static int labelCopyright_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copyright.
        /// </summary>
        internal static string labelCopyright_Text {
            get {
                return ResourceManager.GetString("labelCopyright.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.ContentAlignment semelhante a MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment labelCopyright_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool labelFormTitle_AutoSize {
            get {
                object obj = ResourceManager.GetObject("labelFormTitle.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.ImeMode semelhante a NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode labelFormTitle_ImeMode {
            get {
                object obj = ResourceManager.GetObject("labelFormTitle.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Point semelhante a {X=3,Y=272}.
        /// </summary>
        internal static System.Drawing.Point labelFormTitle_Location {
            get {
                object obj = ResourceManager.GetObject("labelFormTitle.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=35, Height=13}.
        /// </summary>
        internal static System.Drawing.Size labelFormTitle_Size {
            get {
                object obj = ResourceManager.GetObject("labelFormTitle.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 26.
        /// </summary>
        internal static int labelFormTitle_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelFormTitle.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About.
        /// </summary>
        internal static string labelFormTitle_Text {
            get {
                return ResourceManager.GetString("labelFormTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a False.
        /// </summary>
        internal static bool labelFormTitle_Visible {
            get {
                object obj = ResourceManager.GetObject("labelFormTitle.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.DockStyle semelhante a Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle labelProductName_Dock {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Point semelhante a {X=142,Y=0}.
        /// </summary>
        internal static System.Drawing.Point labelProductName_Location {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.Padding semelhante a {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding labelProductName_Margin {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=0, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelProductName_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelProductName.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=269, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelProductName_Size {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 19.
        /// </summary>
        internal static int labelProductName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelProductName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product Name.
        /// </summary>
        internal static string labelProductName_Text {
            get {
                return ResourceManager.GetString("labelProductName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.ContentAlignment semelhante a MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment labelProductName_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelProductName.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.DockStyle semelhante a Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle labelVersion_Dock {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Point semelhante a {X=142,Y=30}.
        /// </summary>
        internal static System.Drawing.Point labelVersion_Location {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.Padding semelhante a {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding labelVersion_Margin {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=0, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelVersion_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelVersion.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=269, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelVersion_Size {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 0.
        /// </summary>
        internal static int labelVersion_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelVersion.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version.
        /// </summary>
        internal static string labelVersion_Text {
            get {
                return ResourceManager.GetString("labelVersion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.ContentAlignment semelhante a MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment labelVersion_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelVersion.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.DockStyle semelhante a Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle logoPictureBox_Dock {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoPictureBox_Image {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Point semelhante a {X=3,Y=3}.
        /// </summary>
        internal static System.Drawing.Point logoPictureBox_Location {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=130, Height=114}.
        /// </summary>
        internal static System.Drawing.Size logoPictureBox_Size {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.PictureBoxSizeMode semelhante a Zoom.
        /// </summary>
        internal static System.Windows.Forms.PictureBoxSizeMode logoPictureBox_SizeMode {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 12.
        /// </summary>
        internal static int logoPictureBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.AnchorStyles semelhante a Bottom, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles okButton_Anchor {
            get {
                object obj = ResourceManager.GetObject("okButton.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Point semelhante a {X=336,Y=278}.
        /// </summary>
        internal static System.Drawing.Point okButton_Location {
            get {
                object obj = ResourceManager.GetObject("okButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=75, Height=23}.
        /// </summary>
        internal static System.Drawing.Size okButton_Size {
            get {
                object obj = ResourceManager.GetObject("okButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 24.
        /// </summary>
        internal static int okButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("okButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;OK.
        /// </summary>
        internal static string okButton_Text {
            get {
                return ResourceManager.GetString("okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 2.
        /// </summary>
        internal static int tableLayoutPanel_ColumnCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.ColumnCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.DockStyle semelhante a Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle tableLayoutPanel_Dock {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.TableLayoutSettings.
        /// </summary>
        internal static System.Windows.Forms.TableLayoutSettings tableLayoutPanel_LayoutSettings {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.LayoutSettings", resourceCulture);
                return ((System.Windows.Forms.TableLayoutSettings)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Point semelhante a {X=9,Y=9}.
        /// </summary>
        internal static System.Drawing.Point tableLayoutPanel_Location {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 6.
        /// </summary>
        internal static int tableLayoutPanel_RowCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.RowCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=414, Height=304}.
        /// </summary>
        internal static System.Drawing.Size tableLayoutPanel_Size {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 0.
        /// </summary>
        internal static int tableLayoutPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.DockStyle semelhante a Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle textBoxDescription_Dock {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Point semelhante a {X=6,Y=123}.
        /// </summary>
        internal static System.Drawing.Point textBoxDescription_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Windows.Forms.Padding semelhante a {Left=6,Top=3,Right=3,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding textBoxDescription_Margin {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Size semelhante a {Width=405, Height=146}.
        /// </summary>
        internal static System.Drawing.Size textBoxDescription_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Int32 semelhante a 23.
        /// </summary>
        internal static int textBoxDescription_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string textBoxDescription_Text {
            get {
                return ResourceManager.GetString("textBoxDescription.Text", resourceCulture);
            }
        }
    }
}
