//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeaturesOverlayPresentation.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeaturesOverlayPresentation.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adding registry keys.
        /// </summary>
        internal static string LOG_ADDING_REG {
            get {
                return ResourceManager.GetString("LOG_ADDING_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing program.
        /// </summary>
        internal static string LOG_CLOSING {
            get {
                return ResourceManager.GetString("LOG_CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detecting operating system.
        /// </summary>
        internal static string LOG_DETECTING_OS {
            get {
                return ResourceManager.GetString("LOG_DETECTING_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do not run on boot.
        /// </summary>
        internal static string LOG_DISABLE_BOOT {
            get {
                return ResourceManager.GetString("LOG_DISABLE_BOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Absent employee.
        /// </summary>
        internal static string LOG_EMPLOYEEAWAY {
            get {
                return ResourceManager.GetString("LOG_EMPLOYEEAWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee present.
        /// </summary>
        internal static string LOG_EMPLOYEEPRESENT {
            get {
                return ResourceManager.GetString("LOG_EMPLOYEEPRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gathering image files.
        /// </summary>
        internal static string LOG_ENUM_FILES {
            get {
                return ResourceManager.GetString("LOG_ENUM_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formatting.
        /// </summary>
        internal static string LOG_FORMAT_SERVICE {
            get {
                return ResourceManager.GetString("LOG_FORMAT_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Found image directory.
        /// </summary>
        internal static string LOG_IMG_FOUND {
            get {
                return ResourceManager.GetString("LOG_IMG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Image directory not found.
        /// </summary>
        internal static string LOG_IMG_NOTFOUND {
            get {
                return ResourceManager.GetString("LOG_IMG_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maintenance.
        /// </summary>
        internal static string LOG_MAINTENANCE_SERVICE {
            get {
                return ResourceManager.GetString("LOG_MAINTENANCE_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not adding registry keys.
        /// </summary>
        internal static string LOG_NOT_ADDING_REG {
            get {
                return ResourceManager.GetString("LOG_NOT_ADDING_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deleting a record in the database.
        /// </summary>
        internal static string LOG_NOTSCHEDULING {
            get {
                return ResourceManager.GetString("LOG_NOTSCHEDULING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset number.
        /// </summary>
        internal static string LOG_PATR_NUM {
            get {
                return ResourceManager.GetString("LOG_PATR_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registering delivery.
        /// </summary>
        internal static string LOG_REGISTERING_DELIVERY {
            get {
                return ResourceManager.GetString("LOG_REGISTERING_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Undoing registry keys.
        /// </summary>
        internal static string LOG_REMOVING_REG {
            get {
                return ResourceManager.GetString("LOG_REMOVING_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolution error.
        /// </summary>
        internal static string LOG_RESOLUTION_ERROR {
            get {
                return ResourceManager.GetString("LOG_RESOLUTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolution below requirement.
        /// </summary>
        internal static string LOG_RESOLUTION_FAILED {
            get {
                return ResourceManager.GetString("LOG_RESOLUTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Suitable display resolution.
        /// </summary>
        internal static string LOG_RESOLUTION_PASSED {
            get {
                return ResourceManager.GetString("LOG_RESOLUTION_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running main window.
        /// </summary>
        internal static string LOG_RUNNING {
            get {
                return ResourceManager.GetString("LOG_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Creating boot entry.
        /// </summary>
        internal static string LOG_SCHEDULING {
            get {
                return ResourceManager.GetString("LOG_SCHEDULING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Service type.
        /// </summary>
        internal static string LOG_SERVICE_TYPE {
            get {
                return ResourceManager.GetString("LOG_SERVICE_TYPE", resourceCulture);
            }
        }
    }
}
