//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeaturesOverlayPresentation.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeaturesOverlayPresentation.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Software created, developed and maintained by Kevin Costa. Programmed in C# using .NET Framework 4.8. Supported systems: Windows 7, 10 and 11.
        ///
        ///    • Copyright © 2023 Kevin Vinícius Teixeira Costa
        ///    • Repository (GitHub): https://github.com/Kevin64/features-overlay-presentation
        ///    • Dependencies repository (GitHub): https://github.com/Kevin64/Dependencies
        ///    • License: (MIT) https://github.com/Kevin64/features-overlay-presentation/blob/master/LICENSE
        ///
        ///This software must be used in conjunction wit [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Advanced options.
        /// </summary>
        public static string lblFixedAdvancedOptionsText {
            get {
                return ResourceManager.GetString("lblFixedAdvancedOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset number:.
        /// </summary>
        public static string lblFixedAssetNumberText {
            get {
                return ResourceManager.GetString("lblFixedAssetNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About.
        /// </summary>
        public static string lblFixedButtonAboutText {
            get {
                return ResourceManager.GetString("lblFixedButtonAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authenticate.
        /// </summary>
        public static string lblFixedButtonAuthenticateText {
            get {
                return ResourceManager.GetString("lblFixedButtonAuthenticateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        public static string lblFixedButtonCloseProgramText {
            get {
                return ResourceManager.GetString("lblFixedButtonCloseProgramText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exit.
        /// </summary>
        public static string lblFixedButtonExitText {
            get {
                return ResourceManager.GetString("lblFixedButtonExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finish.
        /// </summary>
        public static string lblFixedButtonFinishText {
            get {
                return ResourceManager.GetString("lblFixedButtonFinishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next.
        /// </summary>
        public static string lblFixedButtonNextText {
            get {
                return ResourceManager.GetString("lblFixedButtonNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        public static string lblFixedButtonNoText {
            get {
                return ResourceManager.GetString("lblFixedButtonNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password:.
        /// </summary>
        public static string lblFixedButtonPasswordText {
            get {
                return ResourceManager.GetString("lblFixedButtonPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Previous.
        /// </summary>
        public static string lblFixedButtonPreviousText {
            get {
                return ResourceManager.GetString("lblFixedButtonPreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send delivery data.
        /// </summary>
        public static string lblFixedButtonSendDataText {
            get {
                return ResourceManager.GetString("lblFixedButtonSendDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agent:.
        /// </summary>
        public static string lblFixedButtonUsernameText {
            get {
                return ResourceManager.GetString("lblFixedButtonUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        public static string lblFixedButtonYesText {
            get {
                return ResourceManager.GetString("lblFixedButtonYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A corruption was detected in the installation of the 
        ///program. Please reinstall the program and run it again..
        /// </summary>
        public static string lblFixedCorruptionText {
            get {
                return ResourceManager.GetString("lblFixedCorruptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Installation error.
        /// </summary>
        public static string lblFixedCorruptionTitleText {
            get {
                return ResourceManager.GetString("lblFixedCorruptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee present:.
        /// </summary>
        public static string lblFixedEmployeePresentText {
            get {
                return ResourceManager.GetString("lblFixedEmployeePresentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reg. Number:.
        /// </summary>
        public static string lblFixedEmployeeRegistrationNumberText {
            get {
                return ResourceManager.GetString("lblFixedEmployeeRegistrationNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formatting.
        /// </summary>
        public static string lblFixedFormattingText {
            get {
                return ResourceManager.GetString("lblFixedFormattingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incorrect credentials!.
        /// </summary>
        public static string lblFixedIncorrectCredText {
            get {
                return ResourceManager.GetString("lblFixedIncorrectCredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maintenance.
        /// </summary>
        public static string lblFixedMaintenanceText {
            get {
                return ResourceManager.GetString("lblFixedMaintenanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Page:.
        /// </summary>
        public static string lblFixedPageText {
            get {
                return ResourceManager.GetString("lblFixedPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Absent.
        /// </summary>
        public static string lblFixedRadioAbsentText {
            get {
                return ResourceManager.GetString("lblFixedRadioAbsentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Present.
        /// </summary>
        public static string lblFixedRadioPresentText {
            get {
                return ResourceManager.GetString("lblFixedRadioPresentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Watch again?.
        /// </summary>
        public static string lblFixedRelaunchTitleText {
            get {
                return ResourceManager.GetString("lblFixedRelaunchTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want to view the tutorial again?.
        /// </summary>
        public static string lblFixedSeeAgainText {
            get {
                return ResourceManager.GetString("lblFixedSeeAgainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IP:.
        /// </summary>
        public static string lblFixedServerIPText {
            get {
                return ResourceManager.GetString("lblFixedServerIPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Port:.
        /// </summary>
        public static string lblFixedServerPortText {
            get {
                return ResourceManager.GetString("lblFixedServerPortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Service type:.
        /// </summary>
        public static string lblFixedServiceTypeText {
            get {
                return ResourceManager.GetString("lblFixedServiceTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adding registry keys.
        /// </summary>
        public static string LOG_ADDING_REG {
            get {
                return ResourceManager.GetString("LOG_ADDING_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing program.
        /// </summary>
        public static string LOG_CLOSING {
            get {
                return ResourceManager.GetString("LOG_CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detecting operating system.
        /// </summary>
        public static string LOG_DETECTING_OS {
            get {
                return ResourceManager.GetString("LOG_DETECTING_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do not run on boot.
        /// </summary>
        public static string LOG_DISABLE_BOOT {
            get {
                return ResourceManager.GetString("LOG_DISABLE_BOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Absent employee.
        /// </summary>
        public static string LOG_EMPLOYEEAWAY {
            get {
                return ResourceManager.GetString("LOG_EMPLOYEEAWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee present.
        /// </summary>
        public static string LOG_EMPLOYEEPRESENT {
            get {
                return ResourceManager.GetString("LOG_EMPLOYEEPRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gathering image files.
        /// </summary>
        public static string LOG_ENUM_FILES {
            get {
                return ResourceManager.GetString("LOG_ENUM_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formatting.
        /// </summary>
        public static string LOG_FORMAT_SERVICE {
            get {
                return ResourceManager.GetString("LOG_FORMAT_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Found image directory.
        /// </summary>
        public static string LOG_IMG_FOUND {
            get {
                return ResourceManager.GetString("LOG_IMG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Image directory not found.
        /// </summary>
        public static string LOG_IMG_NOTFOUND {
            get {
                return ResourceManager.GetString("LOG_IMG_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maintenance.
        /// </summary>
        public static string LOG_MAINTENANCE_SERVICE {
            get {
                return ResourceManager.GetString("LOG_MAINTENANCE_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not adding registry keys.
        /// </summary>
        public static string LOG_NOT_ADDING_REG {
            get {
                return ResourceManager.GetString("LOG_NOT_ADDING_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deleting a record in the database.
        /// </summary>
        public static string LOG_NOTSCHEDULING {
            get {
                return ResourceManager.GetString("LOG_NOTSCHEDULING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asset number.
        /// </summary>
        public static string LOG_PATR_NUM {
            get {
                return ResourceManager.GetString("LOG_PATR_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registering delivery.
        /// </summary>
        public static string LOG_REGISTERING_DELIVERY {
            get {
                return ResourceManager.GetString("LOG_REGISTERING_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Undoing registry keys.
        /// </summary>
        public static string LOG_REMOVING_REG {
            get {
                return ResourceManager.GetString("LOG_REMOVING_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolution error.
        /// </summary>
        public static string LOG_RESOLUTION_ERROR {
            get {
                return ResourceManager.GetString("LOG_RESOLUTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolution below requirement.
        /// </summary>
        public static string LOG_RESOLUTION_FAILED {
            get {
                return ResourceManager.GetString("LOG_RESOLUTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Suitable display resolution.
        /// </summary>
        public static string LOG_RESOLUTION_PASSED {
            get {
                return ResourceManager.GetString("LOG_RESOLUTION_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running main window.
        /// </summary>
        public static string LOG_RUNNING {
            get {
                return ResourceManager.GetString("LOG_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Creating boot entry.
        /// </summary>
        public static string LOG_SCHEDULING {
            get {
                return ResourceManager.GetString("LOG_SCHEDULING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Service type.
        /// </summary>
        public static string LOG_SERVICE_TYPE {
            get {
                return ResourceManager.GetString("LOG_SERVICE_TYPE", resourceCulture);
            }
        }
    }
}
